language: node.js
node_js:
  - "0.10"
before_install:
 - npm install -g grunt-cli bower
 - npm install -g nightwatch
 - sudo apt-get update
 - sudo apt-get install -y firefox
install: 
 - npm install
 - bower install
 - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
 - sed -i s#.url.*#.url\(\'$PWD.html\'\)#g examples/tests/test.js
before_script:
 - xvfb-run grunt build
script:
 - xvfb-run grunt test
 - java -jar selenium-server-standalone-2.44.0.jar &
 - xvfb-run nightwatch examples/tests/test.js
