language: node.js
node_js:
  - "0.10"
before_install:
 - npm install -g grunt-cli bower
 - sudo apt-get install -y firefox
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
install: 
 - npm install
 - bower install
before_script: xvfb-run grunt build
