language: node.js
node_js:
  - "0.10"
before_install:
 - npm install -g grunt-cli bower
 - sudo apt-get install -y firefox
install: 
 - npm install
 - bower install
before_script:
 - xvfb-run grunt build
script:
 - xvfb-run grunt test
