language: node.js
node_js:
  - "0.10"
before_install:
 - npm install -g grunt-cli bower
 - npm install -g nightwatch
 - sudo apt-get update
 - sudo apt-get install -y firefox
install: 
 - npm install
 - bower install
 - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
 - wget https://www.dropbox.com/s/f0t36562u02pvhx/sftpx.sh
 - sudo chmod +x ./sftpx.sh
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
 - grunt build
 - sed -i s#.url\(.*#.url\(\"file://$PWD/examples/battest/index.html\"\)# examples/tests/test.js
script:
 - grunt test
 - nightwatch examples/tests/test.js
 - cat examples/tests/test.js
