language: node.js
node_js:
  - "0.10"
before_install:
 - npm install -g grunt-cli bower
 - npm install -g nightwatch
 - sudo apt-get update
 - sudo apt-get install -y firefox
 - sudo apt-get install -y sshpass
install: 
 - npm install
 - bower install
 - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
 - grunt build
 - sshpass -p capstone sftp www-data@ec2-54-213-122-61.us-west-2.compute.amazonaws.com:capstone
 - lcd examples/battest
 - mput firefoxos.js index.html app.js
 - exit
script:
 - grunt test
 - nightwatch examples/tests/test.js
